Color for blocks
EPAM-Online-Courses/teatrees-prejap3 pull request #31
Opened 2022-01-24 14:12 UTC by ihor-sukhorada

- Add Color class and unit test for it
- Coloring dot during printing. The ANSI code depends on the number of bytes inside the grid. There are 12 different colors. The O block is filled with red.

2022-01-24 14:50 UTC, pkierat-epam commented on src/main/java/com/epam/prejap/teatrees/game/Color.java
> +        String getANSI() {
You could save a lot of lines of code by storing it as a field in enum and passing the value via constructor.

2022-01-24 15:02 UTC, pkierat-epam commented
Since you're making a decision to bind the value of a dot with a color, it should be clearly documented so that people working on other issues follow this convention. (You might want to invite them review your PR.)

2022-01-24 15:03 UTC, pkierat-epam commented
Also, please bump up the version in the POM.

2022-01-24 15:37 UTC, ihor-sukhorada commented on src/main/java/com/epam/prejap/teatrees/game/Color.java
> +        String getANSI() {
Done.

2022-01-24 15:43 UTC, ihor-sukhorada commented
> Since you're making a decision to bind the value of a dot with a color, it should be clearly documented so that people working on other issues follow this convention. (You might want to invite them review your PR.)

I wish I could replace the type of dot value with an instance of the class, which includes Color reference, but I have to rewrite all game logic. That's why I made this desicion.

2022-01-24 15:44 UTC, ihor-sukhorada commented
> Also, please bump up the version in the POM.

From 0.1 to 0.2 ?

2022-01-24 16:42 UTC, ihor-sukhorada commented
- Update pom version to 0.2
- Add documentation to the Color class and colorDot method

2022-01-25 07:28 UTC, pkierat-epam requested changes

2022-01-25 07:28 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/teatrees/game/ColorTest.java
> +        assertEquals(color.getANSI(), code);
This test seems to be testing the JVM. We don't usually test getters, and checking if an enum contains the values it was told to contain is redundant.

2022-01-25 07:28 UTC, pkierat-epam commented on src/main/java/com/epam/prejap/teatrees/game/Printer.java
> +        return "\033[0;" + colors[dot - 1] + "m" + "#" + "\033[0m";
In line 29, there's already an escape sequence using Unicode syntax instead of octal. While it's not a big problem, it's still an inconsistency.

Also, to increase readability, it might be a good thing to extract the logic related to ANSI to a separate class (might be a utility class).

2022-01-25 07:28 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/teatrees/game/ColorTest.java
> +    public static Object[][] colorASCI() {
Actually, it's "ASCII" not "ASCI" (double "I"). And it's not exactly even ASCII-related.

2022-01-25 07:28 UTC, pkierat-epam commented on src/main/java/com/epam/prejap/teatrees/game/Printer.java
> +    private String colorDot(byte dot) {
This code is not tested. And since it's private, there should be at least a test which causes the method to be invoked.

2022-01-25 07:31 UTC, pkierat-epam commented
> > Since you're making a decision to bind the value of a dot with a color, it should be clearly documented so that people working on other issues follow this convention. (You might want to invite them review your PR.)
> 
> I wish I could replace the type of dot value with a class, which includes Color reference, but I have to rewrite all game logic. That's why I made this decision.

I really like this idea. You can consider it as a follow-up to this issue. But for now, let's at least inform anyone else (via Javadoc) that the value of the dot is not binary anymore.

2022-01-27 10:36 UTC, pkierat-epam commented
Hmmm... it seems you forgot to book the issue for yourself. And now we have two competing solutions for the same function ;-)

2022-01-27 10:40 UTC, asilenko commented
> Hmmm... it seems you forgot to book the issue for yourself. And now we have two competing solutions for the same function ;-)

Not really. We have two very similar issues:
https://github.com/EPAM-Online-Courses/teatrees-prejap3/issues/16
https://github.com/EPAM-Online-Courses/teatrees-prejap3/issues/27

2022-01-28 08:11 UTC, ihor-sukhorada commented
Well, it's kinda strange. Now we have 2 (almost) identical pull requests. I could close my pull request and focus on other issue.

2022-02-01 12:18 UTC, ihor-sukhorada commented
* Refactor Color enum class
* Add Dot interface and classes, which implement them(EmptyDot and ColoredDot)
* Add support of coloring the blocks in the entire application

TODO:
* tests for Color, EmptyDot, and ColoredDot classes
* add javadocs

I've made those changes on my branch in the forked repository. Link below:
https://github.com/ihor-sukhorada/teatrees-prejap3/pull/1

@jaGda

2022-02-04 07:34 UTC, marcin-ogorzalek-EPAM commented
Closing this one as it is being done in https://github.com/EPAM-Online-Courses/teatrees-prejap3/pull/59

2022-02-04 07:34 UTC, closed without merging