Fix executable jar not working
EPAM-Online-Courses/teatrees-prejap3 pull request #32
Opened 2022-01-24 14:12 UTC by deetree

Changed main class FQN in pom.xml, so the jar can be properly built
and launched.

2022-01-24 15:08 UTC, pkierat-epam requested changes
Where are tests that prove this task is working?

2022-01-24 15:14 UTC, deetree commented
How can I check it? Run the jar through test code?

2022-01-25 07:40 UTC, pkierat-epam requested changes

2022-01-25 07:40 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/teatrees/JarTest.java
> +public class JarTest {
Have you tried to run this as a part of Maven lifecycle? Since it's a regular test (no group, no IT, no maven-failsafe-plugin in the POM), it's gonna be executed in the "test" phase along with the rest of unit tests. But this test is definitely not a unit test, since it touches the filesystem.

Moreover, since it's executed in the test phase, and the jar is built in the "package" phase which is after the tests, the test will simply fail.

Try running this:
```
mvn clean verify
```

2022-01-25 07:40 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/teatrees/JarTest.java
> +                .orElse(null);
So if there's no jar file, the method will return `null`, and this will cause the test below to throw NPE instead of failing...

2022-01-27 10:38 UTC, pkierat-epam requested changes
Please bump up the version.

2022-01-27 15:55 UTC, deetree commented
> Please bump up the version.

Done

2022-01-29 18:52 UTC, pkierat-epam approved these changes
Well done. To be merged during the lecture on Monday.

2022-01-30 07:41 UTC, marcin-ogorzalek-EPAM commented
@deetree BTW with the approval you probably may work on another PR :P

2022-01-31 07:42 UTC, pkierat-epam approved these changes
Minor changes, not required for merge.

2022-01-31 07:42 UTC, pkierat-epam commented on pom.xml
> +                            <goal>verify</goal>
This is not necessary, since `integration-test` is executed prior to `verify`.

2022-01-31 07:42 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/teatrees/JarIT.java
> +        Assert.assertNotNull(file, "The file must not be null");
`Assert` could be statically imported.

2022-01-31 07:42 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/teatrees/JarIT.java
> +                .orElse(null);
An exception could be thrown here instead of returning `null`.

2022-01-31 07:42 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/teatrees/JarIT.java
> +public class JarIT {
It would be nice to check if the jar can be executed.

2022-01-31 08:31 UTC, merged