1-add-L-block
EPAM-Online-Courses/teatrees-prejap3 pull request #34
Opened 2022-01-24 14:54 UTC by deetree

Add L block to the playground

2022-01-24 15:24 UTC, deetree commented
Yes, now I know it shouldn't be here for now. Don't be mad at me. I'm still learning 😉

2022-02-07 10:00 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/block/LBlockTest.java
> + */
You know that this is unnecessary by convention?

2022-02-07 10:01 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/block/LBlockTest.java
> + */
Of course in tests

2022-02-07 10:04 UTC, marcin-ogorzalek-EPAM requested changes
one thing for removal

2022-02-07 10:12 UTC, marcin-ogorzalek-EPAM approved these changes

2022-02-07 10:13 UTC, merged