#29 Blocks are falling to the left side
EPAM-Online-Courses/teatrees-prejap3 pull request #35
Opened 2022-01-24 15:28 UTC by asilenko

#29
Bug is fixed.
I have added tests to prove it. I had to add surefire plugin to pom.xml as the implicit version did not work with TestNG successPercentage.

2022-01-24 22:01 UTC, ekrzjan commented
I do not like that tests. They will require modification for any new Move.

2022-01-24 22:26 UTC, asilenko commented
> I do not like that tests. They will require modification for any new Move.

What other random move are you planning to add?

2022-01-24 23:15 UTC, ekrzjan commented
E.g. rotation - my issue #9.

2022-01-25 04:55 UTC, asilenko commented
> E.g. rotation - my issue #11 :)

I think rotation is different kind of move.

2022-01-25 06:37 UTC, asilenko commented
I'll try to make more universal tests.

2022-01-25 07:50 UTC, pkierat-epam requested changes

2022-01-25 07:50 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/teatrees/player/RandomPlayerTest.java
> +    @Test(groups = "nextMove", successPercentage = 25, invocationCount = 100)
Testing randomness is tricky. Relying on successPercentage might cause the test to become [flaky](https://docs.gitlab.com/ee/development/testing_guide/flaky_tests.html), and flaky tests are harmful because they provide no real information about the state of the system, and instead they just waste the team's time forcing them to investigate the issue.

2022-01-25 08:48 UTC, asilenko commented on src/test/java/com/epam/prejap/teatrees/player/RandomPlayerTest.java
> +    @Test(groups = "nextMove", successPercentage = 25, invocationCount = 100)
Acceptance criteria force flaky tests. I'm not sure how to approach this.

2022-01-25 09:18 UTC, ekrzjan commented on src/test/java/com/epam/prejap/teatrees/player/RandomPlayerTest.java
> +    @Test(groups = "nextMove", successPercentage = 25, invocationCount = 100)
Sorry for sticking my nose into your issue, but the randomness is so interesting part that I would like to learn more :) @pkierat-epam What about the mathematical evaluation of false failure? Can I use an MonteCarlo technique - in this case repeat test and check the success percentage - when I can prove that false failure is really rare? For example: 0.00005%? 

This case is described by binomial distribution - success ratio is p = 1/3, failure is q = 2/3, the number of probes is set to n = 100. We can approximate this with normal distribution, because both p*n and q*n are big enough. Expected value for this is p*n ~ 33.3 with standard deviation sqrt(n*p*q) ~ 4.7. We can see, that the 33.3 is bigger than 25 by 1.75 of standard deviation, what gives us 10% of false failure. But with bigger numbers as n = 1000, we can get mean ~ 333 with standard deviation ~ 15. Ratio (333 - 250)/15 is greater than 5 what gives us less than 0.00005% probability of false failure. 1000 is not so big that can not be tested here.

2022-01-25 13:44 UTC, asilenko commented
New test added. It will work even after adding new possible moves.

2022-01-27 10:51 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/teatrees/player/RandomPlayerTest.java
> +    @Test(groups = "nextMove", successPercentage = 25, invocationCount = 100)
While using MonteCarlo is an interesting idea, I was rather thinking about removing the randomness from the tests. Now, how to do that? Here are some of the options:
1. You can mock the Random class and make it return a fixed sequence of numbers (of your choice). There are at least three ways to do this (and I'll leave it to you to find them).
2. You can force the Random class to return the same sequence every time (of course, only in tests). After all, there's no true randomness in classical computers, only pseudo-random.

2022-01-27 13:30 UTC, AndriiV-EPAM commented
Speaking about randomness, I found a nice little article about a random generator
https://boallen.com/random-numbers.html
as well as a question on StackExchange
https://softwareengineering.stackexchange.com/questions/121568/php-rand-function-or-not-so-rand

2022-01-28 07:05 UTC, asilenko commented
New test added.

2022-01-28 20:57 UTC, asilenko commented
Squashed few commits.

2022-01-29 19:56 UTC, pkierat-epam requested changes
One cosmetic change, one - not exactly, but still optional, but the Javadoc is mandatory for this PUBLIC API. I could live without it, if there was one on the class, but there's none. You're just one step away from approval.

2022-01-29 19:56 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/teatrees/player/RandomPlayerTest.java
> +        this.counter = -1;
This could be done in the field initializer instead of the constructor.

2022-01-29 19:56 UTC, pkierat-epam commented on src/main/java/com/epam/prejap/teatrees/player/RandomPlayer.java
> +    public RandomPlayer(Random random) {
Since you're adding a public constructor, it would be sound to consider more general type than Random. (I know, it was there when you came.) Java 17 introduced an interface called java.util.random.RandomGenerator, which could later allow to mock the randomness using something as simple as a lambda.

2022-01-29 19:56 UTC, pkierat-epam commented on src/main/java/com/epam/prejap/teatrees/player/RandomPlayer.java
> +    public RandomPlayer(Random random) {
Where's Javadoc for this PUBLIC constructor?

2022-01-29 21:05 UTC, asilenko commented on src/main/java/com/epam/prejap/teatrees/player/RandomPlayer.java
> +    public RandomPlayer(Random random) {
Added.

2022-01-29 21:06 UTC, asilenko commented on src/test/java/com/epam/prejap/teatrees/player/RandomPlayerTest.java
> +        this.counter = -1;
Done.

2022-01-29 21:08 UTC, asilenko commented on src/main/java/com/epam/prejap/teatrees/player/RandomPlayer.java
> +    public RandomPlayer(Random random) {
Changed to RandomGenerator, but I don't know how to replace MyRandom with lambda in tests.

2022-01-29 21:11 UTC, asilenko commented
Can I squash my commits again or would you like to track changes?

2022-01-30 19:57 UTC, pkierat-epam commented on src/main/java/com/epam/prejap/teatrees/player/RandomPlayer.java
> +    public RandomPlayer(Random random) {
There's no need to do it.

2022-01-30 19:58 UTC, pkierat-epam approved these changes

2022-01-30 20:06 UTC, asilenko commented on src/main/java/com/epam/prejap/teatrees/player/RandomPlayer.java
> +    public RandomPlayer(Random random) {
But I want to know...

2022-01-31 08:52 UTC, merged