Increase game speed
EPAM-Online-Courses/teatrees-prejap3 pull request #36
Opened 2022-01-25 13:37 UTC by KamKoz92

Increase game speed by decreasing delay between cycles.
The delay decreases by 100 ms every 10 points and is capped at 100ms.

2022-01-28 08:59 UTC, marcin-ogorzalek-EPAM commented on pom.xml
> +        <version.plugin.maven.enforcer>3.0.0</version.plugin.maven.enforcer>
Good change.

2022-01-28 08:59 UTC, marcin-ogorzalek-EPAM commented on pom.xml
> +                            <mainClass>com.epam.prejap.teatrees.TeaTrees</mainClass>
Very nice change, I like this.

2022-01-28 09:00 UTC, marcin-ogorzalek-EPAM commented on pom.xml
> +                <version>${version.plugin.maven.surefire}</version>
Nice that you used `properties` for the plugin's version.

2022-01-28 09:01 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/game/Waiter.java
> +     * @since 0.2
0.2 or 0.3?

2022-01-28 09:03 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/WaiterTest.java
> +     */
By convention, tests don't have javadoc. Unless those beings information about some kind of trickiness in those.

2022-01-28 09:04 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/WaiterTest.java
> +    @Test(dataProvider = "waiter")
I like the data provider

2022-01-28 09:06 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/WaiterTest.java
> +                { new Waiter(500), 0, 500, 10 },
As `new Waiter` is always with 500 them maybe:

1. extract it from dprov
2. creat non-final, non-static, `private` filed of that type in this class
3. inisialise the filed in a `void` method annotated with `@BeforeMethod`

2022-01-28 09:06 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/WaiterTest.java
> +        Assert.assertTrue(Math.abs(actualTime - expectedTime) < possibleError);
use static import to get rid off `Assert`

2022-01-28 09:10 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/WaiterTest.java
> +                { new Waiter(500), 0, 500, 10 },
or jest initialise it inside of the test method.

2022-01-28 09:13 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/WaiterTest.java
> +                { new Waiter(500), 1, 400, 10 },
Also, `possibleError` maybe just a constant.

2022-01-28 16:18 UTC, KamKoz92 commented on src/test/java/com/epam/prejap/teatrees/game/WaiterTest.java
> +                { new Waiter(500), 0, 500, 10 },
Fix applied. Will this change performance in any way or, is it just to reduce code repetition?

2022-01-28 16:21 UTC, KamKoz92 commented on src/test/java/com/epam/prejap/teatrees/game/WaiterTest.java
> +        Assert.assertTrue(Math.abs(actualTime - expectedTime) < possibleError);
All in overall static imports are good code practice, or is it up to the programmer to use it one way or another?

2022-01-29 20:11 UTC, pkierat-epam requested changes
Overall good changes. The PR is a candidate for merging soon once the changes are done.

2022-01-29 20:11 UTC, pkierat-epam commented on pom.xml
> +                            <mainClass>com.epam.prejap.teatrees.TeaTrees</mainClass>
Nice indeed, but it's in scope of another issue (#32 ). While I understand the reasons, I don't think there's a test for this change here, and thus it should not be committed.

2022-01-29 20:11 UTC, pkierat-epam commented on src/main/java/com/epam/prejap/teatrees/game/Waiter.java
> +        if (score % 10 == 0 && milliseconds > 100) {
The value `100` is hard-coded. Twice.

2022-01-29 20:11 UTC, pkierat-epam commented on src/main/java/com/epam/prejap/teatrees/game/Waiter.java
> +     * Constructs a newly allocated {@code Waiter} object with an internal
The phrase "Constructs a newly allocated (...) object" is applicable to any constructor (by definition), so I would say it's redundant.

2022-01-30 07:33 UTC, marcin-ogorzalek-EPAM commented on pom.xml
> +                            <mainClass>com.epam.prejap.teatrees.TeaTrees</mainClass>
Yeah, probably (and unfortunately).

2022-01-30 07:35 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/WaiterTest.java
> +                { new Waiter(500), 0, 500, 10 },
Improve readability. Remember, you read more code than you created.

2022-01-30 07:36 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/WaiterTest.java
> +        waiter = new Waiter(500);
With this approach, you may just remove the field completely and use only local variables.

2022-01-30 07:37 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/WaiterTest.java
> +        Assert.assertTrue(Math.abs(actualTime - expectedTime) < possibleError);
In this case, improve readablity. We are here after the type of assertion and the class name is just noise that we need to filter.

2022-01-30 07:39 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/WaiterTest.java
> +    private final int possibleError = 10;
CONSTANT_HAS_DIFFERENT_NAMING_SCHEME by Java convention :P

2022-01-30 11:37 UTC, KamKoz92 commented on src/main/java/com/epam/prejap/teatrees/game/Waiter.java
> +     * Constructs a newly allocated {@code Waiter} object with an internal
Hmm, I thought it would be fine since I saw it in the documentation of standard java classes.

2022-01-30 11:39 UTC, KamKoz92 commented on src/test/java/com/epam/prejap/teatrees/game/WaiterTest.java
> +    private final int possibleError = 10;
Ahh, such a simple mistake, again :D

2022-01-30 11:46 UTC, KamKoz92 commented on src/main/java/com/epam/prejap/teatrees/game/Waiter.java
> +        if (score % 10 == 0 && milliseconds > 100) {
I replaced values with the constant, but I am unsure if this is the best solution.

2022-01-30 11:48 UTC, KamKoz92 commented on pom.xml
> +    <version>0.2</version>
This was fixed in [0529fb8](https://github.com/EPAM-Online-Courses/teatrees-prejap3/pull/36/commits/0529fb87a77fab6c4967741eaf8ea06e444901e8) commit.

2022-01-30 11:49 UTC, KamKoz92 commented on src/test/java/com/epam/prejap/teatrees/game/WaiterTest.java
> +        waiter = new Waiter(500);
Fixed.

2022-01-30 19:44 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/game/Waiter.java
> +     * @since 0.1
0.1 or 0.3?

2022-01-30 19:47 UTC, marcin-ogorzalek-EPAM requested changes
One small fix and it's ready

2022-01-30 22:12 UTC, KamKoz92 commented on src/main/java/com/epam/prejap/teatrees/game/Waiter.java
> +     * @since 0.1
The Waiter class, along with the c-tor and waitForIt method, was introduced in the 0.1 version, but after looking at [@since](https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html#@since) I added java doc for the whole class and put since tag there to clarify that decreaseCycleDelay was added in the later version. I should have written javadoc for Waiter from the start, but I couldn't come up with a good description before :P

2022-01-31 08:58 UTC, marcin-ogorzalek-EPAM commented on .vscode/settings.json
> +}
IIRC this file is from an editor. Shouldn't be included hre. What it's more it should be excluded in `.gitignore`

2022-01-31 08:59 UTC, marcin-ogorzalek-EPAM requested changes
Remove unwanted file, update .gitignore, bump up version

2022-01-31 09:21 UTC, KamKoz92 commented on .vscode/settings.json
> +}
I didn't stage this file in the commit, but somehow it was pushed. I guess changing .gitignore and introducing more conflicts is inevitable :D

2022-01-31 10:36 UTC, KamKoz92 commented
Everything seems to be working now. I increased possible_error in my tests because some failed with the current configuration.

2022-01-31 11:44 UTC, marcin-ogorzalek-EPAM commented on pom.xml
> +</project>
No empty line at the end of the file. Leaving one (for scripts and some tools) is a good practice.

2022-01-31 11:44 UTC, marcin-ogorzalek-EPAM commented on src/test/resources/testng.xml
> +</suite>
No empty line at the end of the file. Leaving one (for scripts and some tools) is a good practice.

2022-01-31 11:45 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/WaiterTest.java
> +    @Test(dataProvider = "waiter", groups = "waitSomeTime")
I would change the name of the group to  `waiting-tests` or something similar

2022-01-31 11:46 UTC, marcin-ogorzalek-EPAM commented on src/test/resources/testng.xml
> +            <define name="waitTimeTest">
The same remark about name

2022-01-31 11:46 UTC, marcin-ogorzalek-EPAM commented on src/test/resources/testng.xml
> +            <define name="waitTimeTest">
as in test class

2022-01-31 11:46 UTC, marcin-ogorzalek-EPAM commented on .gitignore
> +.vscode
I like this change

2022-01-31 12:51 UTC, KamKoz92 commented on src/test/resources/testng.xml
> +            <define name="waitTimeTest">
Changed.

2022-01-31 12:51 UTC, KamKoz92 commented on src/test/java/com/epam/prejap/teatrees/game/WaiterTest.java
> +    @Test(dataProvider = "waiter", groups = "waitSomeTime")
Changed.

2022-01-31 12:51 UTC, KamKoz92 commented on src/test/resources/testng.xml
> +</suite>
Fixed.

2022-01-31 12:52 UTC, KamKoz92 commented on pom.xml
> +</project>
Fixed.

2022-01-31 13:11 UTC, marcin-ogorzalek-EPAM approved these changes

2022-01-31 13:13 UTC, marcin-ogorzalek-EPAM commented
@pkierat-epam I would allow myself to merge it as all the remarks were applied.

2022-01-31 13:18 UTC, merged