Make blocks have different colors
EPAM-Online-Courses/teatrees-prejap3 pull request #41
Opened 2022-01-26 19:20 UTC by jaGda

2022-01-27 11:03 UTC, marcin-ogorzalek-EPAM commented
No description for the pull request. Especially one that closes an issue https://github.com/EPAM-Online-Courses/teatrees-prejap3/issues/27

2022-01-27 11:05 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/PlayfieldTest.java
> + */
By convention, tests shouldn't have javadocs. Those are allowed only when they are meaningful and describes some trickiness in the tests.

2022-01-27 11:05 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/PlayfieldTest.java
> +}
No empty line at the end of the file.

2022-01-27 11:06 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/PlayfieldTest.java
> +}
Add one, every file should have such a line (for different tools and scripting convenience).

2022-01-27 11:07 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/PlayfieldTest.java
> +        // given
I like comments with GWT convention. Keep that onwards.

2022-01-27 11:07 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/PlayfieldTest.java
> +        // given
This comment may be resolved by you @jaGda whenever you want.

2022-01-27 11:12 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/game/Playfield.java
> +        moved = moveDown();
Good change.

2022-01-27 11:15 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/game/Printer.java
> +     * @
Unnecessary empty lien and line with `@`

2022-01-27 11:18 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/game/AnsiColors.java
> +enum AnsiColors {
No javadoc with author and explanation what is this about. I know that by convention those are only needed for `public` objects/methods but you created those for `private`. Thus I would advise describing what we have here.

2022-01-27 11:20 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/game/AnsiColors.java
> +    final String colorCode;
Why not private with overridden `toString`?

2022-01-27 11:21 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/game/Printer.java
> +        return dot == 0 ? " " : AnsiColors.values()[dot - 1].colorCode + "#" + ANSI_RESET;
Referring to the field directly is not a good practice.

2022-01-27 11:23 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/PlayfieldTest.java
> +    private final Playfield playfield = new Playfield(5, 5, new BlockFeed(), new Printer(System.out));
This field should be initialised in some kind of non-static `void` method (setup) annotated with `@BeforeMethod`. 

Unit tests should be independent. Now there is a shared state that may affect those.

2022-01-27 11:28 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/game/Playfield.java
> +    private static byte differentiator = 0;
Should this be `static`? How many instances of `Playfield` we are expecting during one game? IIRC only 1 so this may be an instance field.

2022-01-27 11:33 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/game/Printer.java
> +        out.format(formatter(dot));
Not tested. There are means to "hijack" output and assert it against the expected one.

2022-01-27 11:36 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/PlayfieldTest.java
> +public class PlayfieldTest {
In tests here you are checking the `private` method. This is not away. You should test the `public`/`protected`/package-private method that calls `updateDifferentiator` method. So indirect/black-box testing.

2022-01-27 17:44 UTC, jaGda commented on src/test/java/com/epam/prejap/teatrees/game/PlayfieldTest.java
> + */
ok

2022-01-27 17:45 UTC, jaGda commented on src/test/java/com/epam/prejap/teatrees/game/PlayfieldTest.java
> +}
thx - I didn't know that

2022-01-27 18:09 UTC, jaGda commented on src/main/java/com/epam/prejap/teatrees/game/Printer.java
> +        return dot == 0 ? " " : AnsiColors.values()[dot - 1].colorCode + "#" + ANSI_RESET;
```
private String formatter(byte dot) {
        return dot == 0 ? " " : coloring(dot) + "#" + ANSI_RESET;
    }

    private String coloring(byte dot) {
        return AnsiColors.values()[dot - 1].toString();
    }
```

2022-01-27 18:12 UTC, jaGda commented on src/test/java/com/epam/prejap/teatrees/game/PlayfieldTest.java
> +    private final Playfield playfield = new Playfield(5, 5, new BlockFeed(), new Printer(System.out));
```
private Playfield playfield;
    private final Class<Playfield> clazz = Playfield.class;

    @BeforeMethod
    private void beforeMethod(){
        playfield = new Playfield(5, 5, new BlockFeed(), new Printer(System.out));
    }
```

2022-01-27 18:14 UTC, jaGda commented on src/main/java/com/epam/prejap/teatrees/game/Playfield.java
> +    private static byte differentiator = 0;
true :)

2022-01-27 18:39 UTC, jaGda commented on src/main/java/com/epam/prejap/teatrees/game/Printer.java
> +        out.format(formatter(dot));
done

2022-01-27 19:08 UTC, jaGda commented on src/main/java/com/epam/prejap/teatrees/game/Printer.java
> +     * @
done

2022-01-27 19:08 UTC, jaGda commented on src/main/java/com/epam/prejap/teatrees/game/AnsiColors.java
> +    final String colorCode;
done

2022-01-27 20:23 UTC, jaGda commented on src/test/java/com/epam/prejap/teatrees/game/PlayfieldTest.java
> +public class PlayfieldTest {
done

2022-01-28 07:37 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/PrinterTest.java
> +}
No empty line at the end of the file. :D 

You may setup IDE in such a way that it will add this automatically.

2022-01-28 07:41 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/game/AnsiColors.java
> +
An unnecessary empty line. Javadoc shouldn't be split from things from the things it describes.

Additionally missing dot (`.`) at the end of the sentence.

2022-01-28 07:42 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/PlayfieldTest.java
> +}
Still no empty line at the end

2022-01-28 07:44 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/game/AnsiColors.java
> +    WHITE("\u001B[37m"),
Probably unnecessary comma at the end. Minor issue.

2022-01-28 07:45 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/game/Printer.java
> +        return dot == 0 ? " " : AnsiColors.values()[dot - 1].colorCode + "#" + ANSI_RESET;
I like that you referring to the full change in the comment. :+1:

2022-01-28 07:47 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/PlayfieldTest.java
> +    public void beforeMethod() {
I would advise name `setup` but this is a minor issue

2022-01-28 07:50 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/PrinterTest.java
> +        System.setOut(new PrintStream(output));
Do this in something with `@BeforMethod`. Then restore the original output stream in a method annotated with `@AfterMethod` (`cleanup`). Remember about storing the original stream in the "temporary" field.

Right now this test may affects other ones (even in different classes) if those are using the same technique.

2022-01-28 07:51 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/PrinterTest.java
> +    public void shouldReturnRedText() {
Maybe use a data provider to check all the colours (of course the name of the test should change then).

2022-01-28 07:51 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/PrinterTest.java
> +    public void shouldReturnRedText() {
Alos clearing colors ins not being tested.

2022-01-28 07:55 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/game/Printer.java
> +    private static final String ANSI_RESET = "\u001B[0m";
I think about this one, As this is part of colours maybe it should be constant in the enum. Not sure. 

If it will stay here I think that it may be non-static.

2022-01-28 07:58 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/PlayfieldTest.java
> +    private final Class<Playfield> clazz = Playfield.class;
As you are using this in only one method now I think that it may be a local variable there.

2022-01-28 08:01 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/game/Playfield.java
> +    private byte differentiator = 0;
This name doesn't tell much. It is about colours yeah? So maybe `colorDifferentiator` to indicate what should be different here.

2022-01-28 08:02 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/game/Playfield.java
> +        if (differentiator > AnsiColors.values().length) {
Maye be simplified IIRC to 

```suggestion
        if (++differentiator > AnsiColors.values().length) {
```

Pre-incrementation isnted of post-incerementation

2022-01-28 08:03 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/game/Printer.java
> +    private static final String ANSI_RESET = "\u001B[0m";
If in enum, then gigger visibility or accessor method.

2022-01-28 08:05 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/PlayfieldTest.java
> +public class PlayfieldTest {
Detail here but we should have tests for all cases (so a couple more and repetitive ones required). Or somehow data provider should be used, but I don't have an ide how.

2022-01-28 08:06 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/PlayfieldTest.java
> +}
How do I know? Red mark.
![Screenshot from 2022-01-28 09-05-30](https://user-images.githubusercontent.com/70665397/151510134-d96e6494-aad7-4e2e-b570-3ce418c402a7.png)

2022-01-29 11:31 UTC, jaGda commented on src/test/java/com/epam/prejap/teatrees/game/PlayfieldTest.java
> +}
ready - finally :)

2022-01-29 11:32 UTC, jaGda commented on src/test/java/com/epam/prejap/teatrees/game/PrinterTest.java
> +}
I did it in the IDE :)

2022-01-29 11:36 UTC, jaGda commented on src/main/java/com/epam/prejap/teatrees/game/AnsiColors.java
> +
done

2022-01-29 11:42 UTC, jaGda commented on src/main/java/com/epam/prejap/teatrees/game/AnsiColors.java
> +    WHITE("\u001B[37m"),
done

2022-01-29 11:45 UTC, jaGda commented on src/test/java/com/epam/prejap/teatrees/game/PlayfieldTest.java
> +    public void beforeMethod() {
done

2022-01-29 12:04 UTC, jaGda commented on src/test/java/com/epam/prejap/teatrees/game/PrinterTest.java
> +        System.setOut(new PrintStream(output));
done
```
public class PrinterTest {
    private static PrintStream originalPrintStream;
    private static ByteArrayOutputStream output;

    @BeforeMethod
    public void setUpStreams() {
        originalPrintStream = System.out;
        output = new ByteArrayOutputStream();
        System.setOut(new PrintStream(output));
    }

    @AfterMethod
    public void cleanUpStreams() {
        System.setOut(originalPrintStream);
    }
```

2022-01-29 13:01 UTC, jaGda commented on src/test/java/com/epam/prejap/teatrees/game/PrinterTest.java
> +    public void shouldReturnRedText() {
```
public class ColorsDP {

    @DataProvider(name = "ansi-colors")
    public static Object[][] dpMethod() {
        return new Object[][]{
                {(byte) 1, "\u001B[30m#\u001B[0m"},
                {(byte) 2, "\u001B[31m#\u001B[0m"},
                {(byte) 3, "\u001B[32m#\u001B[0m"},
                {(byte) 4, "\u001B[33m#\u001B[0m"},
                {(byte) 5, "\u001B[34m#\u001B[0m"},
                {(byte) 6, "\u001B[35m#\u001B[0m"},
                {(byte) 7, "\u001B[36m#\u001B[0m"},
                {(byte) 8, "\u001B[37m#\u001B[0m"},
        };
    }

}

@Test(dataProvider = "ansi-colors", dataProviderClass = ColorsDP.class)
    public void shouldReturnTheAvailableColorPalette(byte colorIndicator, String colorCode) {
        // given
        Printer printer = new Printer(System.out);
        //when
        printer.print(colorIndicator);
        //then
        assertEquals(output.toString(), colorCode);
    }
```

2022-01-29 13:22 UTC, jaGda commented on src/main/java/com/epam/prejap/teatrees/game/Printer.java
> +    private static final String ANSI_RESET = "\u001B[0m";
I'm not sure
private final String colorCode;
 
 ```
enum AnsiColors ...

 private static final String ANSI_RESET = "\u001B[0m";

    AnsiColors(String colorCode) {
        this.colorCode = colorCode;
    }

    public String coloringMark(String mark) {
        return colorCode + mark + ANSI_RESET;
    }
class Printer ...
private String formatter(byte dot) {
        return dot == 0 ? " " : coloring(dot);
    }

    private String coloring(byte dot) {
        return AnsiColors.values()[dot - 1].coloringMark("#");
    }
```

2022-01-29 15:54 UTC, jaGda commented on src/test/java/com/epam/prejap/teatrees/game/PlayfieldTest.java
> +    private final Class<Playfield> clazz = Playfield.class;
```
private final Class<Playfield> clazz = Playfield.class;
    private static PrintStream originalPrintStream;
    private Playfield playfield= new Playfield(2, 2, new BlockFeed(), new Printer(System.out));


    @BeforeMethod
    public void setUpFields() {
        originalPrintStream = System.out;
        ByteArrayOutputStream output = new ByteArrayOutputStream();
        System.setOut(new PrintStream(output));
        playfield = new Playfield(2, 2, new BlockFeed(), new Printer(System.out));
    }
```

2022-01-29 16:03 UTC, jaGda commented on src/main/java/com/epam/prejap/teatrees/game/Playfield.java
> +    private byte differentiator = 0;
Yes - that doesn't say much. I changed it as instructed.

2022-01-29 16:17 UTC, jaGda commented on src/main/java/com/epam/prejap/teatrees/game/Playfield.java
> +        if (differentiator > AnsiColors.values().length) {
done

2022-01-29 18:11 UTC, jaGda commented on src/test/java/com/epam/prejap/teatrees/game/PlayfieldTest.java
> +public class PlayfieldTest {
```
@Test(dataProvider = "multiplicity-counter")
    public void shouldIncreaseColorDifferentiator(int expected, int[] methodMultiplier) throws IllegalAccessException {
        // given & when
        for (int i : methodMultiplier) {
            playfield.nextBlock();
        }
        byte colorDifferentiator = getColorDifferentiator(clazz);
        // then
        assertEquals(colorDifferentiator, expected);
    }

@DataProvider(name = "multiplicity-counter")
    private Object[][] dataProvider() {
        return new Object[][]{
                {1, new int[1]},
                {2, IntStream.rangeClosed(1, 2).toArray()},
                {3, IntStream.rangeClosed(1, 3).toArray()},
                {4, IntStream.rangeClosed(1, 4).toArray()},
                {5, IntStream.rangeClosed(1, 5).toArray()},
                {6, IntStream.rangeClosed(1, 6).toArray()},
                {7, IntStream.rangeClosed(1, 7).toArray()},
                {8, IntStream.rangeClosed(1, 8).toArray()},
                {0, IntStream.rangeClosed(1, 9).toArray()},
                {1, IntStream.rangeClosed(1, 10).toArray()},
                {2, IntStream.rangeClosed(1, 11).toArray()},
                {3, IntStream.rangeClosed(1, 12).toArray()},
                {4, IntStream.rangeClosed(1, 13).toArray()}
        };
    }
```

2022-01-29 18:43 UTC, jaGda commented on src/test/java/com/epam/prejap/teatrees/game/PlayfieldTest.java
> +public class PlayfieldTest {
https://github.com/jaGda/teatrees-prejap3/commit/5e5232ce969d251c83e755722020a2e5a49f9cd6

2022-01-30 07:11 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/PlayfieldTest.java
> +    private final Class<Playfield> clazz = Playfield.class;
Not what I was thinking about, but OK. I may stay that way.

2022-01-30 07:15 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/PlayfieldTest.java
> +public class PlayfieldTest {
Either I :D but I see this in changes.

2022-01-30 07:16 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/game/Printer.java
> +    private static final String ANSI_RESET = "\u001B[0m";
I'm approving this

2022-01-30 07:17 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/game/AnsiColors.java
> +    private static final String ANSI_RESET = "\u001B[0m";
Reorder those, as `static` should go before non-static (by convention).

2022-01-30 07:19 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/PrinterTest.java
> +    @Test(dataProvider = "ansi-colors", dataProviderClass = ColorsDP.class)
I think that extracting this data provider to another class is unnecessary. It is good practice, but when more than one is done so.

2022-01-30 07:20 UTC, marcin-ogorzalek-EPAM requested changes
Two minor changes and we can merge this during tomorrow's lecture.

2022-01-30 12:59 UTC, jaGda commented on src/main/java/com/epam/prejap/teatrees/game/AnsiColors.java
> +    private static final String ANSI_RESET = "\u001B[0m";
done

2022-01-30 13:10 UTC, jaGda commented on src/test/java/com/epam/prejap/teatrees/game/PrinterTest.java
> +    @Test(dataProvider = "ansi-colors", dataProviderClass = ColorsDP.class)
done

2022-01-30 19:43 UTC, marcin-ogorzalek-EPAM approved these changes

2022-02-04 07:34 UTC, marcin-ogorzalek-EPAM commented
Closing this one as it is being done in https://github.com/EPAM-Online-Courses/teatrees-prejap3/pull/59

2022-02-04 07:34 UTC, closed without merging