22 Ghost piece implemented
EPAM-Online-Courses/teatrees-prejap3 pull request #49
Opened 2022-01-29 18:21 UTC by pkobylchak

Closes #22

2022-01-30 09:15 UTC, marcin-ogorzalek-EPAM commented
No javadocs for `public` method. No tests. No possibility for merging right now.

2022-01-30 09:15 UTC, marcin-ogorzalek-EPAM commented
BTW bump up the project version in `pom.xml`

2022-01-30 13:47 UTC, pkobylchak commented
> 

I already have 0.2 in my repo. Should I still bump it?

2022-02-03 13:08 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/game/Printer.java
> +            : "#")
this probably may be hide in `private` method

2022-02-03 13:09 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/game/Printer.java
> +            : "#")
weird formatting. rather should be in one line, maybe two (excluding part into `private` method may help)

2022-02-03 13:10 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/block/BrickActionTest.java
> +      { new OBlock() }
I think that now we have at least one additional block that may be used for testing.

2022-02-03 13:11 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/block/BrickActionTest.java
> +    dataProvider = "brickActionDataProvider")
weird formatting. should be rather in one line

2022-02-03 13:11 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/block/BrickActionTest.java
> +    // Given dp
```suggestion
    // Given
```

mentionig of dp int this comment in unnecessary. her and onwards

2022-02-03 13:14 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/BlockShadowTest.java
> +      sa.assertEquals(expectedOut.toString(), actualOut.toString());
I would divide checking initial gird and one with move into two tests

2022-02-03 13:15 UTC, marcin-ogorzalek-EPAM commented on pom.xml
> +    <version>0.8</version>
now it should be 0.9 :D

2022-02-03 13:15 UTC, marcin-ogorzalek-EPAM requested changes
Minor fixes and it is ready to go.

2022-02-04 14:25 UTC, marcin-ogorzalek-EPAM requested changes

2022-02-04 14:25 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/game/Grid.java
> +    static final char SHADOW_SYMBOL = '.';
why not private?

2022-02-04 14:25 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/game/Printer.java
> +    private static char getSymbol(byte dot) {
why `static`? Non method here is being static

2022-02-04 14:25 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/block/BrickActionTest.java
> +    expectedExceptions = ArrayIndexOutOfBoundsException.class)
wierd formatting

2022-02-04 15:00 UTC, asilenko commented on src/test/java/com/epam/prejap/teatrees/block/BrickActionTest.java
> +    expectedExceptions = ArrayIndexOutOfBoundsException.class)
It is unusual formatting but is it bad? It is easier to read than one line.

2022-02-04 15:43 UTC, pkobylchak commented on src/main/java/com/epam/prejap/teatrees/game/Grid.java
> +    static final char SHADOW_SYMBOL = '.';
Was used in other class, now extracted to BrickRepresentation enum

2022-02-04 15:44 UTC, pkobylchak commented on src/main/java/com/epam/prejap/teatrees/game/Printer.java
> +    private static char getSymbol(byte dot) {
To specify explicitly that this method requires no instance. Now extracted to BrickRepresentation enum.

2022-02-04 15:44 UTC, pkobylchak commented on src/test/java/com/epam/prejap/teatrees/block/BrickActionTest.java
> +    expectedExceptions = ArrayIndexOutOfBoundsException.class)
Did not fit 120 symbol line. Now fits.

2022-02-07 08:34 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/block/BrickActionTest.java
> +      { new ZBlock() }
Probably needs updated, as there are 2 new blocks

2022-02-07 08:35 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/block/BrickActionTest.java
> +    final var SYM = (byte) new Random().nextInt(Byte.MAX_VALUE);
why break Java naming convention with this variable?

2022-02-07 08:37 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/block/BrickActionTest.java
> +  public void brickActionHappyPath(Block block) {
name of the test `shouldIndicateWhatReseltShouldBe_givenAtStartWas_whenSomethingHappend`. BTW it may break Java naming convantion.

Here you can find more abut this https://dzone.com/articles/7-popular-unit-test-naming

2022-02-07 08:39 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/block/BrickActionTest.java
> +    Assert.fail();
Why not static impoert?

2022-02-07 08:40 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/BlockShadowTest.java
> +    Assert.assertEquals(expectedOut.toString(), actualOut.toString());
static import

2022-02-07 08:40 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/BlockShadowTest.java
> +    Assert.assertEquals(expectedOut.toString(), actualOut.toString());
static import

2022-02-07 08:41 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/BlockShadowTest.java
> +    Assert.assertEquals(expectedOut.toString(), actualOut.toString());
Generally use static imports for assertion. `Assert` class is just noise that decreases readability.

2022-02-07 09:15 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/PlayfieldTest.java
> +        playfield.col       = 1;
here and onwards

2022-02-07 09:16 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/GhostBlockTestScenarios.java
> +class GhostBlockTestScenarios {
One of the rare occasions when javadocs are needed around tests (or classes created for those).

2022-02-07 09:16 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/block/SingleBlockFeeds.java
> +public enum SingleBlockFeeds {
One of the rare occasions when javadocs are needed around tests (or classes created for those).

2022-02-07 09:17 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/block/SingleBlockFeeds.java
> +public enum SingleBlockFeeds {
Another thing is that it does not necessarily should be in this package.

2022-02-07 09:27 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/BlockShadowTest.java
> +         var actualPs = new PrintStream(actualOut, true)) {
If I understand this correctly, you wish to test output against the expected one. The not fully correct solution here.
It should go as follows (similar things in other, not merged PRs yet e.g. https://github.com/EPAM-Online-Courses/teatrees-prejap3/pull/37/files)

* initilise `Printer` with `System.out` as usual
* in `setup` annotated with `@BeforeMethod` use `Sysytem.setOut`
* as parameter there pass `new ByteArrayOutputStream()`
* in test do whatever necessary to have correct print (normal game logic)
* assert this instance of `ByteArrayOutputStream.toString` against what it should be in form of `String`

2022-02-07 09:28 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/BlockShadowTest.java
> +         var actualPs = new PrintStream(actualOut, true)) {
remember about the `cleanup` method annotated with `@AfterMethod` to restore `System.out` as original output target

2022-02-08 18:52 UTC, pkobylchak commented on src/test/java/com/epam/prejap/teatrees/game/BlockShadowTest.java
> +         var actualPs = new PrintStream(actualOut, true)) {
Nice solution. Thanks

2022-02-09 07:52 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/block/BlockFeed.java
> +    public Block get() {
Maybe make this implementation to call old `nextBlock()` to maintain the stability of `public` API.

2022-02-09 08:03 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/block/SingleBlockFeeds.java
> +public enum SingleBlockFeeds {
Shouldn't be plural

2022-02-09 08:16 UTC, merged