#3 add s block
EPAM-Online-Courses/teatrees-prejap3 pull request #50
Opened 2022-01-30 13:40 UTC by mr-tompkins

Closes #3

2022-01-30 14:04 UTC, asilenko commented on src/test/java/com/epam/prejap/teatrees/block/SBlockTest.java
> +@Test(groups ="semi-useful")
Why is this group called "semi-useful"?

2022-01-30 14:16 UTC, asilenko commented on pom.xml
> +                            <mainClass>com.epam.prejap.teatrees.TeaTrees</mainClass>
https://github.com/EPAM-Online-Courses/teatrees-prejap3/pull/36#pullrequestreview-865848283

2022-01-30 14:23 UTC, mr-tompkins commented on src/test/java/com/epam/prejap/teatrees/block/SBlockTest.java
> +@Test(groups ="semi-useful")
As I understand this tests only checks ones ability to fill an array correctly, but I am open to any suggestions :)

2022-01-30 14:24 UTC, mr-tompkins commented on pom.xml
> +                            <mainClass>com.epam.prejap.teatrees.TeaTrees</mainClass>
Ok, thx I will change that.

2022-02-03 13:31 UTC, marcin-ogorzalek-EPAM commented on pom.xml
> +                            <mainClass>com.epam.prejap.tetris.Tetris</mainClass>
Bad change, the original version fixed a bug. You trying to introduce it once more.

2022-02-03 13:31 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/block/SBlockTest.java
> +    SBlock sBlock;
this may be `private`

2022-02-03 13:32 UTC, marcin-ogorzalek-EPAM commented
Update project's version in `pom.xml.

2022-02-03 13:33 UTC, marcin-ogorzalek-EPAM commented
And sync your branch with the code from `master` in the main repo.

2022-02-03 13:33 UTC, marcin-ogorzalek-EPAM requested changes
Close to be done, but there are things to improve

2022-02-04 09:57 UTC, marcin-ogorzalek-EPAM approved these changes
Seems fine. Maybe Tests could be improved but for now, it's ok.

2022-02-05 20:11 UTC, pkierat-epam approved these changes
Looks good.

2022-02-05 20:11 UTC, merged