23 implement saving player highest score in .txt file
EPAM-Online-Courses/teatrees-prejap3 pull request #51
Opened 2022-01-30 14:41 UTC by Svetlanazub

Implemented feature

2022-01-31 06:23 UTC, marcin-ogorzalek-EPAM commented
You have to bump up the project's version in pom.
Also, there is no link to the issue in the description, especially one closing the issue on merge.

2022-01-31 06:23 UTC, marcin-ogorzalek-EPAM commented on pom.xml
> +        <maven.assembly.plugin.version>3.3.0</maven.assembly.plugin.version>
The name of this variable breaks an already established naming convention.

2022-01-31 06:24 UTC, marcin-ogorzalek-EPAM commented on pom.xml
> +        <maven.assembly.plugin.version>3.3.0</maven.assembly.plugin.version>
Why after removal `jar` plugin variable for it is still present?

2022-01-31 06:24 UTC, marcin-ogorzalek-EPAM commented on pom.xml
> +            <version>2.8.7</version>
why not in `properties`?

2022-01-31 06:25 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/HighestStoredScoresTest.java
> + */
By convention, tests shouldn't have javadocs. Unless there are some trickiness in the tests themselves.

2022-01-31 06:27 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/HighestStoredScores.java
> +    private final String path;
Reorder those. Constant should be first.

2022-01-31 06:28 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/PlayerScore.java
> +    private final String name;
Wrong intentation.

2022-01-31 06:29 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/SavedScoreIOUtility.java
> +class SavedScoreIOUtility {
Why this class was created as a helper?

2022-01-31 06:41 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/HighestStoredScores.java
> +            throw new IllegalArgumentException("File don't find!");
Are we catching this somehow or are we just crashing the app? I didn't spot try-catch for it in main or somewhere else.

2022-01-31 06:42 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/SavedScoreIOUtility.java
> +                    throw new IllegalArgumentException("You are first player!");
Are we catching this somehow or are we just crashing the app? I didn't spot try-catch for it in main or somewhere else.

2022-01-31 06:43 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/HighestStoredScores.java
> +        StringBuilder input = new StringBuilder();
Why name `input`?

2022-01-31 06:44 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/HighestStoredScoresTest.java
> +    @BeforeClass(groups = {"IntegrationHighestStoredScoresTests"})
I like an establishment of tests' groups

2022-01-31 06:47 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/PlayerScore.java
> +class PlayerScore implements Comparable<PlayerScore> {
Why not record?

2022-02-03 13:35 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/HighestStoredScoresTest.java
> +public class HighestStoredScoresTest {
As this read file, I think that this is an integration test.

2022-02-03 13:36 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/HighestStoredScoresTest.java
> +public class HighestStoredScoresTest {
or rather we have a mix here. Divide those into two classes. One with unit tests and one with integrational.

2022-02-03 13:38 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/HighestStoredScoresTest.java
> +            fail();
`assertFalse` may be used instead

2022-02-03 13:39 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/HighestStoredScoresTest.java
> +    public void setUp() {
for readability this should be place before the first test

2022-02-03 13:42 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/TeaTrees.java
> +        int delay = 5;
why the delay has decreased?

2022-02-03 13:44 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/TeaTrees.java
> +        final String nameJSONFile = "score_list.json";
```suggestion
        final String scoreListFileName = "score_list.json";
```

JSONFile name is meaningless, doesn't tell what this is really about.

2022-02-03 13:47 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/SavedScoreIOUtility.java
> +        private static BufferedReader getBufferedReader(String name) {
Why `BufferReader` as a return type. Is this multithread?

2022-02-03 13:50 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/SavedScoreIOUtility.java
> +            return new BufferedReader(streamReader);
I'm not a fan of this method. `BufferedReader` and `InputStream` should be closed at the end of use. What is more those should be close by try-with-resources.

2022-02-03 13:52 UTC, marcin-ogorzalek-EPAM requested changes
A couple of things to improve here. 
Remember about syncing your branch with the `master` on the main repo. 
Bump up the project's version in `pom.xml`. Update `testng.xml`
And link this PR to the proper issue via `Closes #23` in the description

2022-02-04 07:36 UTC, marcin-ogorzalek-EPAM commented
As I had been informed, this probably won't be developed any further in the closest future. Probably for closing @pkierat-epam

2022-02-04 08:07 UTC, Svetlanazub commented
@pkierat-epam I'll be able to finish the task in some next days so I close it and someone can do it.

2022-02-04 08:07 UTC, closed without merging