Fix issue #9: Add Y block
EPAM-Online-Courses/teatrees-prejap3 pull request #58
Opened 2022-02-01 21:03 UTC by jsayev

- Add YBlock class;
- Add javadocs for YBlock;
- Add tests for YBlock class;
- Update package version from 0.7 to 0.8;

Closes #9

2022-02-03 13:57 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/block/YBlockTest.java
> +    public void shouldHaveExpectedValuesAtCoordinatesFromDP(int rowIndex, int colIndex, int expectedValue) {
```suggestion
    public void shouldHaveExpectedValuesAtGivenCoordinates(int rowIndex, int colIndex, int expectedValue) {
```

2022-02-03 13:59 UTC, marcin-ogorzalek-EPAM requested changes
Remember to sync with the main repo. It is close to being merged I think

2022-02-03 16:35 UTC, jsayev commented on src/test/java/com/epam/prejap/teatrees/block/YBlockTest.java
> +    public void shouldHaveExpectedValuesAtCoordinatesFromDP(int rowIndex, int colIndex, int expectedValue) {
Done

2022-02-05 15:31 UTC, jsayev commented on pom.xml
> -    <version>0.9</version>
actually 0.9 is my version prior to merge (which brings 0.10) and my change updates it to 0.11

2022-02-07 07:16 UTC, marcin-ogorzalek-EPAM approved these changes

2022-02-07 07:18 UTC, merged