Implement "random obstacles on the field" feature
EPAM-Online-Courses/teatrees-prejap3 pull request #65
Opened 2022-02-09 10:40 UTC by jsayev

- Add `Flags` class to hold game flags;
- Add `FlagSeparator` helper class to extract flags out of program arguments;
- Add test for `Flags` and `FlagSeparator` classes;
- Add `public void setFieldPriorToTheGame(int gameDifficulty)` method to `PlayField` to manipulate game grid;
- Update package version;

Closes #19

2022-02-09 11:10 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/FlagsTest.java
> +}
No empty line at the end of the file. It good practice to leave one for some tools and scripts

2022-02-09 11:16 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/TeaTrees.java
> +        this.flags = flags;
The name `flag` (here and as a type) doesn't bring any meaning. It is a level difficulty switch/modifier. Think about better name name

2022-02-09 11:17 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/helpers/FlagSeparator.java
> +public class FlagSeparator {
It is not a separator, it is a parser. We are parsing `args`  here.

2022-02-09 11:18 UTC, marcin-ogorzalek-EPAM commented on src/test/resources/testng.xml
> +                <include name="helpers"/>
Rather utilities the helpers

2022-02-09 11:19 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/helpers/FlagSeparatorTest.java
> +@Test(groups = "helpers")
Rather utilities then helpers

2022-02-09 11:22 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/helpers/FlagSeparator.java
> +        HashMap<String, String> flagToValuePairs = new HashMap<>();
```suggestion
        Map<String, String> flagToValuePairs = new HashMap<>();
```

2022-02-09 11:22 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/helpers/FlagSeparator.java
> +        HashMap<String, String> flagToValuePairs = new HashMap<>();
If it is possible use interface types, not the concert ones.

2022-02-09 11:24 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/helpers/FlagSeparator.java
> +            flagToValuePairs.put(flagOption, value);
Do you know that multiline lambdas are discouraged? Refractor this. In the worst-case scenario extract body of this lambda to a `private` method and call it.

2022-02-09 11:26 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/helpers/FlagSeparator.java
> +            flagToValuePairs.put(flagOption, value);
Also considering normalisation of the parameter, so it would be case insensitive.

2022-02-09 11:27 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/helpers/FlagSeparator.java
> +     * @return {@link Map} of {@link String} type key and {@link String} type value
What are those keys and values? You know we can read that those are of `String` type but it gives us nothing more

2022-02-09 11:30 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/game/Flags.java
> +public class Flags {
Maybe this should be an enum responsible for difficulty levels. Or maybe there should be one and this should have `EnamMap` for mapping those to argument/number of starting obstacles?

2022-02-09 11:31 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/game/Flags.java
> +public class Flags {
BTW name `Flag` is a little meh. It should indicate what is this real responsibility is.

What if there would be another set of startup parameters to parse? How to extend this class then

2022-02-09 11:34 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/game/Playfield.java
> +     * Builds playground with random blocks based on gameDifficulty set through flags during runtime.<br/>
```suggestion
     * Builds starting game field with a random number of blocks based on game difficulty. This is being set through a proper starting parameter.<br/>
```

2022-02-09 11:37 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/game/Playfield.java
> +        randomizeGround(obstacleCount, grid.getGrid(), feed);
Could be don wit strategy design pattern if there would be a proper concept.

2022-02-09 11:38 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/teatrees/game/Playfield.java
> +    private void randomizeGround(int obstacleCount, byte[][] grid, BlockSupplier feed) {
What if the place on the gird is beating already taken by another obstacle?

2022-02-09 11:39 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/FlagsTest.java
> +        HashMap<String, String> expectedMapOfFlags = new HashMap<>();
Why concrete type for the variable?

2022-02-09 11:40 UTC, marcin-ogorzalek-EPAM commented on src/test/java/com/epam/prejap/teatrees/game/FlagsTest.java
> +        HashMap<String, String> expectedMapOfFlags = new HashMap<>();
Here and onwards

2022-02-09 11:43 UTC, marcin-ogorzalek-EPAM requested changes
There are things to do

2022-02-09 14:33 UTC, jsayev commented on src/test/java/com/epam/prejap/teatrees/game/FlagsTest.java
> +}
Done.

2022-02-09 15:01 UTC, jsayev commented on src/main/java/com/epam/prejap/teatrees/TeaTrees.java
> +        this.flags = flags;
I named it that way for the future flags intended for different purposes.Just in case.

2022-02-09 15:03 UTC, jsayev commented on src/main/java/com/epam/prejap/teatrees/helpers/FlagSeparator.java
> +public class FlagSeparator {
Done.

2022-02-09 15:08 UTC, jsayev commented on src/test/java/com/epam/prejap/teatrees/helpers/FlagSeparatorTest.java
> +@Test(groups = "helpers")
Done

2022-02-09 15:11 UTC, jsayev commented on src/main/java/com/epam/prejap/teatrees/helpers/FlagSeparator.java
> +        HashMap<String, String> flagToValuePairs = new HashMap<>();
done

2022-02-09 16:56 UTC, jsayev commented on src/main/java/com/epam/prejap/teatrees/helpers/FlagSeparator.java
> +            flagToValuePairs.put(flagOption, value);
guess done.

2022-02-09 17:09 UTC, jsayev commented on src/main/java/com/epam/prejap/teatrees/helpers/FlagSeparator.java
> +     * @return {@link Map} of {@link String} type key and {@link String} type value
removed unnecessary part

2022-02-09 17:54 UTC, jsayev commented on src/main/java/com/epam/prejap/teatrees/game/Playfield.java
> +    private void randomizeGround(int obstacleCount, byte[][] grid, BlockSupplier feed) {
I couldn't implement that logic. I know what you mean but that logic is overkill for me :)

2022-02-13 15:14 UTC, jsayev commented on src/main/java/com/epam/prejap/teatrees/game/Flags.java
> +public class Flags {
It already holds all other flags for the game.

2022-02-15 11:46 UTC, closed without merging